
language: node_js
node_js:
  - 8
before_install:
  - "curl -L https://raw.githubusercontent.com/arunoda/travis-ci-laika/6a3a7afc21be99f1afedbd2856d060a02755de6d/configure.sh | /bin/sh"
services:
  - mongodb
env:
  - LAIKA_OPTIONS="-t 5000"
  cache:
  directories:
    - npm
    - node_modules
install:
  - npm install
  - ./install-dependencies.sh
script:
  - node_modules/.bin/cypress run --record --key 5d04f046-0c08-44d5-9f7a-23197cc060cb