
language: node_js
node_js:
  - 8

  cache:
  directories:
    - npm
    - node_modules
install:
  - npm install
  - ./install-dependencies.sh
script:
  - cypress run --record --key 5d04f046-0c08-44d5-9f7a-23197cc060cb