
version: 2
jobs:
  build:
    docker:
      - image: cypress/base:6
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/app
    steps:
      - checkout
      - run: npm install
      - run: node_modules/cypress run --record --key 5d04f046-0c08-44d5-9f7a-23197cc060cb